spring.application.name=back-end

# Conexão com o Supabase (Transaction Pooler, schema techmob)
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?currentSchema=techmob&prepareThreshold=0
spring.datasource.username=postgres.rdqbrsjfbndcyglrfswm
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=techmob
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Actuator/Health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

server.port=8080