spring.application.name=back-end

# Conexão com o Supabase (Session Pooler, schema techmob)
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?currentSchema=techmob
spring.datasource.username=postgres.rdqbrsjfbndcyglrfswm
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=techmob
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080